version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/cms
      - SECRET_KEY=dev-secret
      - MEDIA_PROVIDER=local
    volumes:
      - ./:/app
      - ./instance:/app/instance
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cms
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
